// Converts "Córdoba Capital" → "cordoba-capital"
export function slugify(str: string): string {
  return str
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // strip accents
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');
}

// Approximate reverse: "cordoba-capital" → "Cordoba Capital"
export function unslugify(slug: string): string {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

// slug → exact city name (as stored in MongoDB)
export const CITY_SLUG_MAP: Record<string, string> = {
  'cordoba-capital':                        'Córdoba Capital',
  'san-miguel-de-tucuman':                  'San Miguel de Tucumán',
  'villa-maria':                            'Villa María',
  'parana':                                 'Paraná',
  'san-juan':                               'San Juan',
  'santa-fe':                               'Santa Fe',
  'resistencia':                            'Resistencia',
  'posadas':                                'Posadas',
  'merlo':                                  'Merlo',
  'alta-gracia':                            'Alta Gracia',
  'yerba-buena':                            'Yerba Buena',
  'ushuaia':                                'Ushuaia',
  'corrientes':                             'Corrientes',
  'gba-oeste':                              'GBA Oeste',
  'rosario':                                'Rosario',
  'santa-rosa':                             'Santa Rosa',
  'villa-carlos-paz':                       'Villa Carlos Paz',
  'bariloche':                              'Bariloche',
  'san-salvador-de-jujuy':                  'San Salvador de Jujuy',
  'gba-norte':                              'GBA Norte',
  'salta':                                  'Salta',
  'neuquen':                                'Neuquén',
  'comodoro-rivadavia':                     'Comodoro Rivadavia',
  'san-fernando-del-valle-de-catamarca':    'San Fernando del Valle de Catamarca',
  'buenos-aires-capital':                   'Buenos Aires Capital',
  'mendoza':                                'Mendoza',
  'gba-sur':                                'GBA Sur',
  'santiago-del-estero':                    'Santiago del Estero',
  'rio-cuarto':                             'Río Cuarto',
  'la-rioja':                               'La Rioja',
  'formosa':                                'Formosa',
  // Tourist & regional cities
  'cafayate':                               'Cafayate',
  'tilcara':                                'Tilcara',
  'purmamarca':                             'Purmamarca',
  'san-martin-de-los-andes':                'San Martín de los Andes',
  'villa-la-angostura':                     'Villa La Angostura',
  'junin-de-los-andes':                     'Junín de los Andes',
  'el-bolson':                              'El Bolsón',
  'el-calafate':                            'El Calafate',
  'el-chalten':                             'El Chaltén',
  'puerto-madryn':                          'Puerto Madryn',
  'trelew':                                 'Trelew',
  'puerto-iguazu':                          'Puerto Iguazú',
  'mina-clavero':                           'Mina Clavero',
  'la-falda':                               'La Falda',
  'cosquin':                                'Cosquín',
  'santa-rosa-de-calamuchita':              'Santa Rosa de Calamuchita',
  'tandil':                                 'Tandil',
  'pinamar':                                'Pinamar',
  'villa-gesell':                           'Villa Gesell',
  'carilo':                                 'Cariló',
  // Tanda 2
  'mar-del-plata':                          'Mar del Plata',
  'bahia-blanca':                           'Bahía Blanca',
  'la-plata':                               'La Plata',
  'necochea':                               'Necochea',
  'rafaela':                                'Rafaela',
  'venado-tuerto':                          'Venado Tuerto',
  'concordia':                              'Concordia',
  'gualeguaychu':                           'Gualeguaychú',
  'san-rafael':                             'San Rafael',
  'godoy-cruz':                             'Godoy Cruz',
  'obera':                                  'Oberá',
  'jesus-maria':                            'Jesús María',
  'villa-allende':                          'Villa Allende',
  'unquillo':                               'Unquillo',
  'zapala':                                 'Zapala',
  'plottier':                               'Plottier',
  'general-roca':                           'General Roca',
  'cipolletti':                             'Cipolletti',
  // Tanda 3
  'viedma':                                 'Viedma',
  'san-antonio-oeste':                      'San Antonio Oeste',
  'rio-grande':                             'Río Grande',
  'rawson':                                 'Rawson',
  'esquel':                                 'Esquel',
  'rio-ceballos':                           'Río Ceballos',
  'saldan':                                 'Saldán',
  'mendiolaza':                             'Mendiolaza',
  'bell-ville':                             'Bell Ville',
  'tartagal':                               'Tartagal',
  'paso-de-los-libres':                     'Paso de los Libres',
  'mercedes':                               'Mercedes',
  'maipu':                                  'Maipú',
  'lujan-de-cuyo':                          'Luján de Cuyo',
  // Tanda 4
  'san-luis':                               'San Luis',
  'rio-gallegos':                           'Río Gallegos',
  'pergamino':                              'Pergamino',
  'san-nicolas-de-los-arroyos':             'San Nicolás de los Arroyos',
  'zarate':                                 'Zárate',
  'campana':                                'Campana',
  'olavarria':                              'Olavarría',
  'reconquista':                            'Reconquista',
  'concepcion-del-uruguay':                 'Concepción del Uruguay',
  'san-martin-mendoza':                     'San Martín',
  'eldorado':                               'Eldorado',
  'villa-del-totoral':                      'Villa del Totoral',
  'arroyito':                               'Arroyito',
  'centenario':                             'Centenario',
  'cutral-co':                              'Cutral Có',
};

// slug → exact province name (as stored in MongoDB)
export const PROVINCE_SLUG_MAP: Record<string, string> = {
  'buenos-aires':          'Buenos Aires',
  'catamarca':             'Catamarca',
  'chaco':                 'Chaco',
  'chubut':                'Chubut',
  'cordoba':               'Córdoba',
  'corrientes':            'Corrientes',
  'entre-rios':            'Entre Ríos',
  'formosa':               'Formosa',
  'jujuy':                 'Jujuy',
  'la-pampa':              'La Pampa',
  'la-rioja':              'La Rioja',
  'mendoza':               'Mendoza',
  'misiones':              'Misiones',
  'neuquen':               'Neuquén',
  'rio-negro':             'Río Negro',
  'salta':                 'Salta',
  'san-juan':              'San Juan',
  'san-luis':              'San Luis',
  'santa-cruz':            'Santa Cruz',
  'santa-fe':              'Santa Fe',
  'santiago-del-estero':   'Santiago del Estero',
  'tierra-del-fuego':      'Tierra del Fuego',
  'tucuman':               'Tucumán',
};

// Province slug → reverse lookup (exact name → slug), for convenience
export const PROVINCE_NAME_TO_SLUG: Record<string, string> = Object.fromEntries(
  Object.entries(PROVINCE_SLUG_MAP).map(([slug, name]) => [name, slug])
);

// City slug → province slug mapping
export const CITY_TO_PROVINCE_SLUG: Record<string, string> = {
  'cordoba-capital':                     'cordoba',
  'villa-maria':                         'cordoba',
  'villa-carlos-paz':                    'cordoba',
  'alta-gracia':                         'cordoba',
  'rio-cuarto':                          'cordoba',
  'san-miguel-de-tucuman':               'tucuman',
  'yerba-buena':                         'tucuman',
  'parana':                              'entre-rios',
  'san-juan':                            'san-juan',
  'santa-fe':                            'santa-fe',
  'rosario':                             'santa-fe',
  'resistencia':                         'chaco',
  'posadas':                             'misiones',
  'merlo':                               'san-luis',
  'ushuaia':                             'tierra-del-fuego',
  'corrientes':                          'corrientes',
  'gba-norte':                           'buenos-aires',
  'gba-oeste':                           'buenos-aires',
  'gba-sur':                             'buenos-aires',
  'buenos-aires-capital':                'buenos-aires',
  'santa-rosa':                          'la-pampa',
  'bariloche':                           'rio-negro',
  'san-salvador-de-jujuy':               'jujuy',
  'salta':                               'salta',
  'neuquen':                             'neuquen',
  'comodoro-rivadavia':                  'chubut',
  'san-fernando-del-valle-de-catamarca': 'catamarca',
  'mendoza':                             'mendoza',
  'santiago-del-estero':                 'santiago-del-estero',
  'la-rioja':                            'la-rioja',
  'formosa':                             'formosa',
  // Tourist & regional cities
  'cafayate':                            'salta',
  'tilcara':                             'jujuy',
  'purmamarca':                          'jujuy',
  'san-martin-de-los-andes':             'neuquen',
  'villa-la-angostura':                  'neuquen',
  'junin-de-los-andes':                  'neuquen',
  'el-bolson':                           'rio-negro',
  'el-calafate':                         'santa-cruz',
  'el-chalten':                          'santa-cruz',
  'puerto-madryn':                       'chubut',
  'trelew':                              'chubut',
  'puerto-iguazu':                       'misiones',
  'mina-clavero':                        'cordoba',
  'la-falda':                            'cordoba',
  'cosquin':                             'cordoba',
  'santa-rosa-de-calamuchita':           'cordoba',
  'tandil':                              'buenos-aires',
  'pinamar':                             'buenos-aires',
  'villa-gesell':                        'buenos-aires',
  'carilo':                              'buenos-aires',
  // Tanda 2
  'mar-del-plata':                       'buenos-aires',
  'bahia-blanca':                        'buenos-aires',
  'la-plata':                            'buenos-aires',
  'necochea':                            'buenos-aires',
  'rafaela':                             'santa-fe',
  'venado-tuerto':                       'santa-fe',
  'concordia':                           'entre-rios',
  'gualeguaychu':                        'entre-rios',
  'san-rafael':                          'mendoza',
  'godoy-cruz':                          'mendoza',
  'obera':                               'misiones',
  'jesus-maria':                         'cordoba',
  'villa-allende':                       'cordoba',
  'unquillo':                            'cordoba',
  'zapala':                              'neuquen',
  'plottier':                            'neuquen',
  'general-roca':                        'rio-negro',
  'cipolletti':                          'rio-negro',
  // Tanda 3
  'viedma':                              'rio-negro',
  'san-antonio-oeste':                   'rio-negro',
  'rio-grande':                          'tierra-del-fuego',
  'rawson':                              'chubut',
  'esquel':                              'chubut',
  'rio-ceballos':                        'cordoba',
  'saldan':                              'cordoba',
  'mendiolaza':                          'cordoba',
  'bell-ville':                          'cordoba',
  'tartagal':                            'salta',
  'paso-de-los-libres':                  'corrientes',
  'mercedes':                            'corrientes',
  'maipu':                               'mendoza',
  'lujan-de-cuyo':                       'mendoza',
  // Tanda 4
  'san-luis':                            'san-luis',
  'rio-gallegos':                        'santa-cruz',
  'pergamino':                           'buenos-aires',
  'san-nicolas-de-los-arroyos':          'buenos-aires',
  'zarate':                              'buenos-aires',
  'campana':                             'buenos-aires',
  'olavarria':                           'buenos-aires',
  'reconquista':                         'santa-fe',
  'concepcion-del-uruguay':              'entre-rios',
  'san-martin-mendoza':                  'mendoza',
  'eldorado':                            'misiones',
  'villa-del-totoral':                   'cordoba',
  'arroyito':                            'cordoba',
  'centenario':                          'neuquen',
  'cutral-co':                           'neuquen',
};

// Province name → cities slugs in that province
export const PROVINCE_CITIES: Record<string, string[]> = {
  'cordoba':            ['cordoba-capital', 'villa-maria', 'villa-carlos-paz', 'alta-gracia', 'rio-cuarto', 'mina-clavero', 'la-falda', 'cosquin', 'santa-rosa-de-calamuchita', 'jesus-maria', 'villa-allende', 'unquillo', 'rio-ceballos', 'saldan', 'mendiolaza', 'bell-ville', 'villa-del-totoral', 'arroyito'],
  'buenos-aires':       ['buenos-aires-capital', 'gba-norte', 'gba-oeste', 'gba-sur', 'tandil', 'pinamar', 'villa-gesell', 'carilo', 'mar-del-plata', 'bahia-blanca', 'la-plata', 'necochea', 'pergamino', 'san-nicolas-de-los-arroyos', 'zarate', 'campana', 'olavarria'],
  'tucuman':            ['san-miguel-de-tucuman', 'yerba-buena'],
  'santa-fe':           ['rosario', 'santa-fe', 'rafaela', 'venado-tuerto', 'reconquista'],
  'mendoza':            ['mendoza', 'san-rafael', 'godoy-cruz', 'maipu', 'lujan-de-cuyo', 'san-martin-mendoza'],
  'salta':              ['salta', 'cafayate', 'tartagal'],
  'jujuy':              ['san-salvador-de-jujuy', 'tilcara', 'purmamarca'],
  'neuquen':            ['neuquen', 'san-martin-de-los-andes', 'villa-la-angostura', 'junin-de-los-andes', 'zapala', 'plottier', 'centenario', 'cutral-co'],
  'rio-negro':          ['bariloche', 'el-bolson', 'general-roca', 'cipolletti', 'viedma', 'san-antonio-oeste'],
  'entre-rios':         ['parana', 'concordia', 'gualeguaychu', 'concepcion-del-uruguay'],
  'chaco':              ['resistencia'],
  'misiones':           ['posadas', 'puerto-iguazu', 'obera', 'eldorado'],
  'san-luis':           ['merlo', 'san-luis'],
  'tierra-del-fuego':   ['ushuaia', 'rio-grande'],
  'corrientes':         ['corrientes', 'paso-de-los-libres', 'mercedes'],
  'la-pampa':           ['santa-rosa'],
  'chubut':             ['comodoro-rivadavia', 'puerto-madryn', 'trelew', 'rawson', 'esquel'],
  'catamarca':          ['san-fernando-del-valle-de-catamarca'],
  'san-juan':           ['san-juan'],
  'santiago-del-estero': ['santiago-del-estero'],
  'la-rioja':           ['la-rioja'],
  'formosa':            ['formosa'],
  'santa-cruz':         ['el-calafate', 'el-chalten', 'rio-gallegos'],
};

// Province → description (for SEO)
export const PROVINCE_DESCRIPTIONS: Record<string, { es: string; en: string; stats: string[] }> = {
  'Buenos Aires': {
    es: 'Buenos Aires es la provincia más poblada de Argentina, con más de 17 millones de habitantes. Rodea la Ciudad Autónoma de Buenos Aires y alberga el Gran Buenos Aires, la mayor área metropolitana del país. Su mercado inmobiliario es el más dinámico y diverso de Argentina.',
    en: 'Buenos Aires is Argentina\'s most populated province, home to over 17 million people. It surrounds the City of Buenos Aires and includes Greater Buenos Aires, the country\'s largest metropolitan area. Its real estate market is the most dynamic and diverse in Argentina.',
    stats: ['17M+ habitantes', 'Mayor mercado inmobiliario del país', 'Acceso a Puerto, aeropuertos y autopistas'],
  },
  'Córdoba': {
    es: 'Córdoba es la segunda provincia más poblada de Argentina y uno de los polos universitarios, industriales y turísticos más importantes del país. Su capital, Córdoba Capital, concentra la mayor demanda de propiedades, mientras que destinos como Villa Carlos Paz y Alta Gracia atraen inversión turística.',
    en: 'Córdoba is Argentina\'s second most populated province and one of its most important university, industrial, and tourism hubs. Its capital concentrates the highest property demand, while destinations like Villa Carlos Paz attract tourist investment.',
    stats: ['3.7M+ habitantes', '2ª provincia por población', 'Hub universitario e industrial'],
  },
  'Mendoza': {
    es: 'Mendoza es la provincia vitivinícola más importante de América Latina y un destino de alta gama para inversores. Su economía combina agricultura de exportación, turismo de lujo y desarrollo inmobiliario en zona andina. El mercado en dólares es muy estable por el ingreso de divisas del turismo internacional.',
    en: 'Mendoza is Latin America\'s most important wine province and a premium destination for investors. Its economy combines export agriculture, luxury tourism, and Andean real estate development. The USD market is very stable thanks to international tourism income.',
    stats: ['Capital del vino latinoamericano', 'USD 1.200M/año en exportaciones', 'Turismo internacional creciente'],
  },
  'Santa Fe': {
    es: 'Santa Fe es el motor agroindustrial de Argentina, concentrando las exportaciones de soja y cereales del mundo. Rosario, su ciudad principal, es el tercer aglomerado urbano del país y tiene un mercado inmobiliario maduro con fuerte demanda de inversores.',
    en: 'Santa Fe is Argentina\'s agro-industrial engine, concentrating world-leading soy and grain exports. Rosario, its main city, is the country\'s third urban agglomerate with a mature real estate market and strong investor demand.',
    stats: ['Eje exportador agroindustrial', 'Rosario: 1.3M+ habitantes', '3er mercado inmobiliario del país'],
  },
  'Salta': {
    es: 'Salta combina un centro histórico colonial con una economía diversificada en turismo, petróleo y agro. Es una de las provincias con mayor crecimiento turístico de Argentina, lo que impulsa el mercado de propiedades de alquiler temporario y desarrollo hotelero.',
    en: 'Salta combines a colonial historic center with a diversified economy spanning tourism, oil, and agriculture. It\'s one of Argentina\'s fastest-growing tourist destinations, driving short-term rental and hotel development markets.',
    stats: ['Centro histórico Patrimonio Nacional', 'Turismo en alza 15%/año', 'Inversión en alquiler temporario'],
  },
  'Tucumán': {
    es: 'Tucumán, la provincia más pequeña de Argentina, es también una de las más densamente pobladas. Su economía agroindustrial y su importante sistema universitario generan alta demanda de propiedades residenciales, especialmente departamentos para estudiantes en San Miguel de Tucumán.',
    en: 'Tucumán, Argentina\'s smallest province, is also one of its most densely populated. Its agro-industrial economy and important university system generate high residential property demand, especially student apartments in San Miguel de Tucumán.',
    stats: ['Provincia más densa del NOA', '3 universidades nacionales', 'Alta demanda estudiantil'],
  },
  'Neuquén': {
    es: 'Neuquén es la capital energética de Argentina, hogar de Vaca Muerta, el segundo yacimiento de shale no convencional más grande del mundo. El boom petrolero y gasífero impulsa una demanda de propiedades muy por encima de la media nacional, con precios en dólares en constante ascenso.',
    en: 'Neuquén is Argentina\'s energy capital, home to Vaca Muerta, the world\'s second-largest unconventional shale reserve. The oil and gas boom drives property demand well above the national average, with USD prices constantly rising.',
    stats: ['Vaca Muerta: 2° reserva shale mundial', 'Crecimiento poblacional acelerado', 'Precios en USD en alza'],
  },
  'Río Negro': {
    es: 'Río Negro alberga a Bariloche, el destino turístico de montaña más importante de Sudamérica. El mercado inmobiliario de Bariloche opera casi exclusivamente en dólares y presenta alta demanda de propiedades para alquiler temporario, segunda residencia e inversión hotelera.',
    en: 'Río Negro is home to Bariloche, South America\'s most important mountain tourist destination. Bariloche\'s real estate market operates almost exclusively in USD with high demand for short-term rentals, second homes, and hotel investment.',
    stats: ['Bariloche: turismo 4 estaciones', 'Mercado 100% USD', 'Revalorización histórica +8%/año'],
  },
  'Jujuy': {
    es: 'Jujuy combina paisajes únicos como la Quebrada de Humahuaca (Patrimonio UNESCO) con una economía en expansión ligada al litio, el turismo y la agroindustria. San Salvador de Jujuy y Tilcara concentran la mayor demanda de propiedades residenciales y turísticas.',
    en: 'Jujuy combines unique landscapes like the UNESCO World Heritage Quebrada de Humahuaca with an expanding economy tied to lithium, tourism, and agro-industry. San Salvador de Jujuy and Tilcara concentrate the highest residential and tourist property demand.',
    stats: ['Triángulo del litio', 'Quebrada de Humahuaca UNESCO', 'Inversión minera en alza'],
  },
  'Entre Ríos': {
    es: 'Entre Ríos, la provincia mesopotámica por excelencia, combina turismo termal, agro y una calidad de vida reconocida en todo el país. Paraná, su capital, ofrece propiedades a precios más accesibles que las grandes ciudades con una calidad urbana destacada.',
    en: 'Entre Ríos, the quintessential Mesopotamian province, combines thermal tourism, agriculture, and a quality of life recognized throughout Argentina. Paraná, its capital, offers more accessible property prices than major cities with outstanding urban quality.',
    stats: ['Capital termal de Argentina', 'Calidad de vida destacada', 'Precios accesibles'],
  },
  'Chaco': {
    es: 'Chaco es una de las provincias del NEA con mayor potencial de crecimiento. Resistencia, su capital, es un importante centro cultural y comercial que concentra la demanda inmobiliaria de toda la región chaqueña.',
    en: 'Chaco is one of the NEA\'s provinces with the greatest growth potential. Resistencia, its capital, is an important cultural and commercial center concentrating real estate demand from the entire Chaco region.',
    stats: ['Centro del NEA', 'Capital cultural regional', 'Precios en ascenso'],
  },
  'Misiones': {
    es: 'Misiones, la provincia de las Cataratas del Iguazú, combina turismo internacional de alto impacto con una economía forestal y yerbatera. Posadas conecta con Paraguay y Brasil, generando un mercado inmobiliario con demanda regional transfronteriza.',
    en: 'Misiones, the province of Iguazú Falls, combines high-impact international tourism with a forestry and yerba mate economy. Posadas connects with Paraguay and Brazil, generating a real estate market with cross-border regional demand.',
    stats: ['Cataratas del Iguazú: UNESCO', '2M+ turistas/año', 'Frontera triple: AR-BR-PY'],
  },
  'San Luis': {
    es: 'San Luis, conocida por su política de promoción industrial y fiscal, atrae inversión empresarial hace décadas. Merlo, en las Sierras Puntanas, es uno de los destinos de segunda residencia y retiro más buscados de Argentina por su clima y paisaje excepcionales.',
    en: 'San Luis, known for its industrial and fiscal promotion policies, has attracted business investment for decades. Merlo, in the Puntanas Sierras, is one of Argentina\'s most sought-after second-home and retirement destinations for its exceptional climate and landscape.',
    stats: ['Polo industrial con exenciones', 'Merlo: clima y naturaleza únicos', 'Jubilados e inversores'],
  },
  'Tierra del Fuego': {
    es: 'Tierra del Fuego, el fin del mundo, es la provincia más austral de la Tierra. Ushuaia combina un mercado de trabajo activo (zona franca industrial, turismo antártico) con un mercado inmobiliario en dólares muy demandado por la escasez de suelo urbanizable.',
    en: 'Tierra del Fuego, the end of the world, is Earth\'s southernmost province. Ushuaia combines an active labor market (industrial free zone, Antarctic tourism) with a highly demanded USD real estate market due to scarce urban land.',
    stats: ['Zona franca industrial', 'Turismo antártico creciente', 'Escasez de suelo urbanizable'],
  },
  'Corrientes': {
    es: 'Corrientes es un importante nodo vial y comercial del NEA, con acceso al MERCOSUR vía el puente General Belgrano. Su mercado inmobiliario se concentra en la capital provincial, con demanda de estudiantes universitarios y empleados públicos.',
    en: 'Corrientes is an important road and commercial hub in the NEA, with MERCOSUR access via the General Belgrano bridge. Its real estate market concentrates in the provincial capital, with demand from university students and public employees.',
    stats: ['Puerta al MERCOSUR', 'Polo universitario regional', 'Precios accesibles'],
  },
  'La Pampa': {
    es: 'La Pampa es el corazón agrícola de Argentina. Santa Rosa, su capital, ofrece propiedades residenciales a precios muy accesibles con buena conectividad con Buenos Aires. Ideal para quienes buscan calidad de vida fuera de los grandes centros urbanos.',
    en: 'La Pampa is Argentina\'s agricultural heartland. Santa Rosa, its capital, offers very affordable residential properties with good connectivity to Buenos Aires. Ideal for those seeking quality of life outside major urban centers.',
    stats: ['Corazón agropecuario', 'Precios muy accesibles', '600km a Buenos Aires por ruta 5'],
  },
  'Chubut': {
    es: 'Chubut alberga a Comodoro Rivadavia, el principal centro petrolero de la Argentina Atlántica. El mercado inmobiliario está fuertemente vinculado a la actividad hidrocarburífera, con alta demanda de vivienda para trabajadores del sector y familias de profesionales.',
    en: 'Chubut is home to Comodoro Rivadavia, the main oil hub of Atlantic Argentina. The real estate market is strongly linked to hydrocarbon activity, with high housing demand from sector workers and professional families.',
    stats: ['Principal polo petrolero patagónico', 'Demanda sostenida de vivienda', 'Mercado en USD activo'],
  },
  'Catamarca': {
    es: 'Catamarca tiene una de las minas de cobre más importantes del mundo (Bajo La Alumbrera) y forma parte del triángulo del litio. San Fernando del Valle de Catamarca, su capital, concentra la actividad inmobiliaria con precios accesibles y creciente demanda minera.',
    en: 'Catamarca has one of the world\'s most important copper mines (Bajo La Alumbrera) and is part of the lithium triangle. San Fernando del Valle de Catamarca, its capital, concentrates real estate activity with affordable prices and growing mining demand.',
    stats: ['Triángulo del litio', 'Minería de cobre y litio', 'Crecimiento por inversión minera'],
  },
  'San Juan': {
    es: 'San Juan combina producción vitivinícola, minería y turismo de montaña. Su capital ofrece un mercado inmobiliario ordenado con precios accesibles y buena calidad de vida, siendo una alternativa atractiva a Mendoza para quienes buscan la región de Cuyo.',
    en: 'San Juan combines wine production, mining, and mountain tourism. Its capital offers an orderly real estate market with affordable prices and good quality of life, making it an attractive alternative to Mendoza for those seeking the Cuyo region.',
    stats: ['2ª provincia vitivinícola', 'Minería de oro y cobre', 'Alternativa a Mendoza'],
  },
  'Santiago del Estero': {
    es: 'Santiago del Estero, la ciudad más antigua de Argentina (1553), tiene un mercado inmobiliario en transformación, impulsado por obra pública y desarrollo agroindustrial. Termas de Río Hondo atrae inversión turística en la provincia.',
    en: 'Santiago del Estero, Argentina\'s oldest city (1553), has a real estate market in transformation, driven by public works and agro-industrial development. Termas de Río Hondo attracts tourist investment in the province.',
    stats: ['Ciudad más antigua de Argentina', 'Termas de Río Hondo', 'Inversión pública en infraestructura'],
  },
  'La Rioja': {
    es: 'La Rioja tiene uno de los mercados inmobiliarios más accesibles de Argentina, con propiedades a precios muy bajos en dólares. La capital provincial ofrece calidad de vida elevada, clima árido soleado y conexión directa con las sierras riojanas.',
    en: 'La Rioja has one of Argentina\'s most affordable real estate markets, with properties at very low USD prices. The provincial capital offers high quality of life, sunny arid climate, and direct connection to the Rioja sierras.',
    stats: ['Precios más accesibles del país', 'Clima árido y soleado', 'Vinicultura artesanal en crecimiento'],
  },
  'Formosa': {
    es: 'Formosa es una de las provincias más septentrionales de Argentina, fronteriza con Paraguay. Su capital concentra la actividad inmobiliaria de la región, con precios muy accesibles y demanda principalmente de empleados públicos y familias locales.',
    en: 'Formosa is one of Argentina\'s northernmost provinces, bordering Paraguay. Its capital concentrates the region\'s real estate activity, with very affordable prices and demand primarily from public employees and local families.',
    stats: ['Frontera con Paraguay', 'Precios muy accesibles', 'Crecimiento demográfico sostenido'],
  },
  'Santa Cruz': {
    es: 'Santa Cruz, en la Patagonia austral, combina riqueza petrolera, gasoductos y turismo de naturaleza con glaciares. Río Gallegos y El Calafate lideran el mercado inmobiliario provincial, con demanda de trabajadores energéticos y turistas de alto poder adquisitivo.',
    en: 'Santa Cruz, in southern Patagonia, combines oil wealth, gas pipelines, and nature tourism with glaciers. Río Gallegos and El Calafate lead the provincial real estate market, with demand from energy workers and high-spending tourists.',
    stats: ['Glaciar Perito Moreno: UNESCO', 'Polo energético patagónico', 'Turismo premium creciente'],
  },
};

// City → description
export const CITY_DESCRIPTIONS: Record<string, { es: string; en: string; barrios?: string[] }> = {
  'Córdoba Capital': {
    es: 'Córdoba Capital es la segunda ciudad más grande de Argentina, con más de 1.5 millones de habitantes. Es un polo universitario de primer nivel con 13 universidades que generan alta demanda de alquileres. El mercado inmobiliario es muy activo, especialmente en barrios como Nueva Córdoba, Güemes y General Paz. Es también un hub industrial y tecnológico con importante presencia de multinacionales.',
    en: 'Córdoba Capital is Argentina\'s second largest city, home to over 1.5 million people. It\'s a top university hub with 13 universities generating high rental demand. The real estate market is very active, especially in neighborhoods like Nueva Córdoba, Güemes, and General Paz. It\'s also an industrial and tech hub with major multinational presence.',
    barrios: ['Nueva Córdoba', 'Güemes', 'General Paz', 'Cerro de las Rosas', 'Villa Belgrano', 'Bimaco', 'Argüello', 'Jardín'],
  },
  'San Miguel de Tucumán': {
    es: 'San Miguel de Tucumán, capital del "Jardín de la República", es la ciudad más importante del NOA. Con una economía basada en la agroindustria azucarera, el comercio y el sector público, ofrece un mercado inmobiliario activo con alta demanda de departamentos para estudiantes y profesionales.',
    en: 'San Miguel de Tucumán, capital of the "Garden of the Republic", is the most important city in the NOA region. With an economy based on sugar agro-industry, commerce, and the public sector, it offers an active real estate market with high demand for student and professional apartments.',
    barrios: ['Centro', 'Yerba Buena', 'San Cayetano', 'Villa 9 de Julio', 'Alderetes'],
  },
  'Villa María': {
    es: 'Villa María es la tercera ciudad más grande de Córdoba, ubicada estratégicamente sobre la Ruta Nacional 9. Con una economía basada en la industria alimentaria, el comercio y la educación universitaria, ofrece propiedades a precios muy accesibles con buena calidad de vida.',
    en: 'Villa María is Córdoba\'s third largest city, strategically located on National Route 9. With an economy based on food industry, commerce, and university education, it offers properties at very affordable prices with good quality of life.',
    barrios: ['Centro', 'Villa Nueva', 'Los Boulevares', 'Villa del Parque'],
  },
  'Paraná': {
    es: 'Paraná es la capital de Entre Ríos, ubicada sobre el río Paraná con frente costero excepcional. Ofrece una calidad de vida reconocida, precios muy accesibles y buena conectividad con Santa Fe. Ideal para quienes buscan escapar de las grandes urbes sin perder servicios.',
    en: 'Paraná is Entre Ríos\' capital, situated on the Paraná river with an exceptional waterfront. It offers recognized quality of life, very affordable prices, and good connectivity to Santa Fe. Ideal for those seeking to escape large cities without losing services.',
    barrios: ['Centro', 'Thompson', 'Bajada Grande', 'General Racedo'],
  },
  'San Juan': {
    es: 'San Juan, capital de la provincia homónima, es un importante centro minero y vitivinícola de la región de Cuyo. Su mercado inmobiliario ofrece propiedades a precios competitivos frente a Mendoza, con una ciudad planificada y buena conectividad.',
    en: 'San Juan, capital of the eponymous province, is an important mining and wine center of the Cuyo region. Its real estate market offers properties at competitive prices compared to Mendoza, with a planned city and good connectivity.',
    barrios: ['Centro', 'Chimbas', 'Rawson', 'Rivadavia'],
  },
  'Santa Fe': {
    es: 'Santa Fe es la capital provincial, un importante nodo universitario, judicial y administrativo. Con acceso al sistema de ríos Paraná-Uruguay, ofrece una vida urbana de calidad con propiedades más accesibles que Rosario.',
    en: 'Santa Fe is the provincial capital, an important university, judicial, and administrative hub. With access to the Paraná-Uruguay river system, it offers quality urban life with more affordable properties than Rosario.',
    barrios: ['Centro', 'Candioti', 'El Pozo', 'Guadalupe'],
  },
  'Resistencia': {
    es: 'Resistencia, capital del Chaco, es conocida como "la ciudad de las esculturas" por su colección de arte público urbano. Es el principal centro comercial y de servicios del noreste argentino, con un mercado inmobiliario en crecimiento impulsado por inversión pública.',
    en: 'Resistencia, capital of Chaco, is known as "the city of sculptures" for its urban public art collection. It\'s the main commercial and services center of northeastern Argentina, with a real estate market growing driven by public investment.',
    barrios: ['Centro', 'Villa Libertad', 'Fontana', 'Barranqueras'],
  },
  'Posadas': {
    es: 'Posadas, capital de Misiones, es la puerta de entrada a las Cataratas del Iguazú y una ciudad con fuerte dinamismo comercial fronterizo con Encarnación, Paraguay. Su mercado inmobiliario combina demanda local con inversión de paraguayos que buscan radicarse en Argentina.',
    en: 'Posadas, capital of Misiones, is the gateway to Iguazú Falls and a city with strong cross-border commercial dynamism with Encarnación, Paraguay. Its real estate market combines local demand with investment from Paraguayans seeking to relocate to Argentina.',
    barrios: ['Centro', 'Villa Lanús', 'Itaembé Miní', 'A3 - 2000'],
  },
  'Merlo': {
    es: 'Merlo, en las Sierras Puntanas de San Luis, es uno de los destinos de segunda residencia más buscados de Argentina. Su microclima excepcional, con 300 días de sol al año, atrae jubilados, trabajadores remotos e inversores de alquiler temporario. La demanda supera históricamente a la oferta.',
    en: 'Merlo, in San Luis\' Puntanas Sierras, is one of Argentina\'s most sought-after second-home destinations. Its exceptional microclimate, with 300 sunny days per year, attracts retirees, remote workers, and short-term rental investors. Demand has historically exceeded supply.',
    barrios: ['Villa de Merlo', 'Los Molles', 'Carpintería', 'El Molino'],
  },
  'Alta Gracia': {
    es: 'Alta Gracia, a 36 km de Córdoba Capital, combina historia (fue residencia del Che Guevara y Manuel de Falla) con un entorno serrano muy valorado. Es una ciudad residencial por excelencia, con alta demanda de casas y countries para familias que trabajan en Córdoba.',
    en: 'Alta Gracia, 36km from Córdoba Capital, combines history (it was home to Che Guevara and Manuel de Falla) with a highly valued mountain setting. It\'s a quintessential residential city with high demand for homes and gated communities for families working in Córdoba.',
    barrios: ['Centro', 'La Serranita', 'Villa Paravachasca', 'Anisacate'],
  },
  'Yerba Buena': {
    es: 'Yerba Buena es el barrio jardín de Tucumán, el municipio más elegante y residencial del Gran Tucumán. Limita con las Sierras del Aconquija y concentra la demanda de propiedades premium: countries, chalets y departamentos de alta gama para profesionales y familias de alto poder adquisitivo.',
    en: 'Yerba Buena is Tucumán\'s garden neighborhood, the most elegant and residential municipality of Greater Tucumán. It borders the Aconquija Sierras and concentrates premium property demand: gated communities, chalets, and high-end apartments for professionals and high-income families.',
    barrios: ['El Corte', 'Los Nogales', 'Cumbres del Sereno', 'San Javier'],
  },
  'Ushuaia': {
    es: 'Ushuaia, la ciudad más austral del mundo habitable, combina una economía de zona franca industrial con turismo antártico y de naturaleza. La escasez de suelo urbanizable (rodeada de montañas y el canal Beagle) hace que los precios en dólares sean de los más altos del sur argentino.',
    en: 'Ushuaia, the world\'s southernmost inhabited city, combines an industrial free zone economy with Antarctic and nature tourism. The scarcity of buildable land (surrounded by mountains and the Beagle Channel) makes USD prices among the highest in southern Argentina.',
    barrios: ['Centro', 'El Volcadero', 'Bahía Encerrada', 'FONAVI'],
  },
  'Corrientes': {
    es: 'Corrientes capital, sobre el Paraná, es el corazón cultural del litoral argentino. Conocida por el Carnaval Correntino y el chamamé (Patrimonio UNESCO), ofrece propiedades accesibles y una calidad de vida elevada para una capital provincial.',
    en: 'Corrientes capital, on the Paraná river, is the cultural heart of Argentina\'s Littoral. Known for the Corrientes Carnival and chamamé (UNESCO Heritage), it offers affordable properties and high quality of life for a provincial capital.',
    barrios: ['Centro', 'Laguna Seca', 'Punta Tacuara', 'Camba Cuá'],
  },
  'GBA Norte': {
    es: 'El GBA Norte comprende los partidos de Vicente López, San Isidro, San Fernando, Tigre, Zona Náutica y alrededores. Es la zona residencial más premium del conurbano bonaerense, con countries, barrios cerrados y acceso directo al Delta del Tigre. Los precios son los más altos del Gran Buenos Aires.',
    en: 'Greater Buenos Aires North includes the districts of Vicente López, San Isidro, San Fernando, Tigre, Zona Náutica, and surroundings. It\'s the most premium residential area of the Buenos Aires suburbs, with gated communities and direct access to the Tigre Delta. Prices are the highest in Greater Buenos Aires.',
    barrios: ['San Isidro', 'Martínez', 'Acassuso', 'Tigre', 'Nordelta', 'Vicente López'],
  },
  'GBA Oeste': {
    es: 'El GBA Oeste cubre los partidos de La Matanza, Morón, Hurlingham, Ituzaingó, Merlo, Moreno y Luján. Es la zona más populosa del conurbano con alta demanda de vivienda para familias de clase media. Ofrece los precios más accesibles del área metropolitana con buena conectividad en tren.',
    en: 'Greater Buenos Aires West covers the districts of La Matanza, Morón, Hurlingham, Ituzaingó, Merlo, Moreno, and Luján. It\'s the most populous area of the suburbs with high housing demand from middle-class families. It offers the most affordable prices in the metropolitan area with good train connectivity.',
    barrios: ['Morón', 'Haedo', 'Ramos Mejía', 'San Justo', 'Luján', 'Ituzaingó'],
  },
  'GBA Sur': {
    es: 'El GBA Sur incluye Lomas de Zamora, Lanús, Avellaneda, Quilmes, Berazategui y La Plata (capital bonaerense). Zona de fuerte demanda estudiantil por la UNLP y con importante mercado de alquileres. Precios intermedios entre el norte y el oeste del conurbano.',
    en: 'Greater Buenos Aires South includes Lomas de Zamora, Lanús, Avellaneda, Quilmes, Berazategui, and La Plata (provincial capital). Area of strong student demand from UNLP and with an important rental market. Prices are intermediate between the north and west suburbs.',
    barrios: ['La Plata', 'Quilmes', 'Avellaneda', 'Lanús', 'Lomas de Zamora'],
  },
  'Buenos Aires Capital': {
    es: 'La Ciudad Autónoma de Buenos Aires es el mayor mercado inmobiliario de Argentina. Con 3 millones de habitantes y más de 2.000 inmobiliarias, ofrece opciones desde monoambientes en Palermo hasta penthouses en Puerto Madero. El mercado opera principalmente en dólares y es el más líquido del país.',
    en: 'The Autonomous City of Buenos Aires is Argentina\'s largest real estate market. With 3 million inhabitants and over 2,000 agencies, it offers options from studio apartments in Palermo to penthouses in Puerto Madero. The market operates mainly in USD and is the country\'s most liquid.',
    barrios: ['Palermo', 'Recoleta', 'Belgrano', 'Puerto Madero', 'San Telmo', 'Villa Crespo', 'Caballito', 'Flores'],
  },
  'Rosario': {
    es: 'Rosario es la tercera ciudad más grande de Argentina y el principal puerto de exportación granaria del mundo. Su mercado inmobiliario es el más activo del interior después de Córdoba, con alta demanda en barrios como Fisherton, Pichincha y Puerto Norte. Es la cuna del fútbol (Messi y Di Stéfano) y tiene una escena gastronómica y cultural destacada.',
    en: 'Rosario is Argentina\'s third largest city and the world\'s main grain export port. Its real estate market is the most active in the interior after Córdoba, with high demand in neighborhoods like Fisherton, Pichincha, and Puerto Norte. It\'s the birthplace of football legends and has a remarkable gastronomy and cultural scene.',
    barrios: ['Fisherton', 'Pichincha', 'Puerto Norte', 'La Florida', 'Alberdi', 'Echesortu'],
  },
  'Santa Rosa': {
    es: 'Santa Rosa, capital de La Pampa, ofrece propiedades a precios muy accesibles con buena conectividad con Buenos Aires. Es una ciudad de tamaño medio con servicios completos, ideal para quienes buscan calidad de vida en el interior sin el costo de las grandes ciudades.',
    en: 'Santa Rosa, capital of La Pampa, offers very affordable properties with good connectivity to Buenos Aires. It\'s a medium-sized city with full services, ideal for those seeking quality of life in the interior without the cost of large cities.',
    barrios: ['Centro', 'Jardín', 'Ranguelco', 'Stella Maris'],
  },
  'Villa Carlos Paz': {
    es: 'Villa Carlos Paz, a 36 km de Córdoba sobre el lago San Roque, es el principal destino turístico de las Sierras Chicas. Con más de 70.000 habitantes permanentes y 2 millones de turistas anuales, ofrece un mercado de alquiler temporario excepcional y alta demanda de segunda residencia.',
    en: 'Villa Carlos Paz, 36km from Córdoba on Lake San Roque, is the main tourist destination of the Sierras Chicas. With over 70,000 permanent residents and 2 million annual tourists, it offers an exceptional short-term rental market and high second-home demand.',
    barrios: ['Centro', 'El Cóndor', 'La Cuesta', 'Las Rosas', 'San Nicolás'],
  },
  'Bariloche': {
    es: 'Bariloche (San Carlos de Bariloche) es el destino turístico de montaña más icónico de Sudamérica. Su mercado inmobiliario opera casi exclusivamente en dólares, con demanda de alquiler temporario los 365 días (ski en invierno, trekking y lagos en verano). La oferta es históricamente escasa frente a la demanda.',
    en: 'Bariloche (San Carlos de Bariloche) is South America\'s most iconic mountain tourist destination. Its real estate market operates almost exclusively in USD, with short-term rental demand 365 days a year (ski in winter, trekking and lakes in summer). Supply is historically scarce relative to demand.',
    barrios: ['Centro', 'El Mallín', 'Melipal', 'Villa Los Coihues', 'Dina Huapi'],
  },
  'San Salvador de Jujuy': {
    es: 'San Salvador de Jujuy es la capital de la provincia más andina de Argentina. Con acceso a la Quebrada de Humahuaca (UNESCO) y en pleno boom del turismo cultural, su mercado inmobiliario crece impulsado por trabajadores mineros del litio y visitantes que eligen quedarse.',
    en: 'San Salvador de Jujuy is the capital of Argentina\'s most Andean province. With access to the UNESCO Quebrada de Humahuaca and in the midst of a cultural tourism boom, its real estate market grows driven by lithium mining workers and visitors who choose to stay.',
    barrios: ['Centro', 'Alto Comedero', 'Villa Gorriti', 'Belgrano'],
  },
  'Salta': {
    es: 'Salta, "la Linda", es una de las ciudades más bellas del NOA con su centro histórico colonial perfectamente conservado. Su mercado inmobiliario tiene dos velocidades: el centro histórico en dólares con alta demanda turística, y los barrios residenciales en pesos con demanda local sostenida.',
    en: 'Salta, "la Linda", is one of the most beautiful cities in the NOA with its perfectly preserved colonial historic center. Its real estate market runs at two speeds: the historic center in USD with high tourist demand, and residential neighborhoods in pesos with sustained local demand.',
    barrios: ['Centro Histórico', 'Tres Cerritos', 'San Lorenzo', 'Limache', 'Portezuelo'],
  },
  'Neuquén': {
    es: 'Neuquén ciudad es el epicentro del boom energético de Vaca Muerta. La demanda de propiedades supera ampliamente a la oferta, generando precios en dólares entre los más altos del interior del país. Inversores de todo el mundo buscan propiedades para alquilar a trabajadores petroleros y gas.',
    en: 'Neuquén city is the epicenter of the Vaca Muerta energy boom. Property demand far exceeds supply, generating USD prices among the highest in the Argentine interior. Investors from around the world seek properties to rent to oil and gas workers.',
    barrios: ['Centro', 'Confluencia', 'Belgrano', 'Alta Barda', 'Parque Industrial'],
  },
  'Comodoro Rivadavia': {
    es: 'Comodoro Rivadavia es el principal centro petrolero de la Argentina atlántica. Su mercado inmobiliario está directamente vinculado a los ciclos de la industria hidrocarburífera, con alta demanda de propiedades de alquiler para trabajadores del sector de todo el país.',
    en: 'Comodoro Rivadavia is the main oil center of Atlantic Argentina. Its real estate market is directly tied to hydrocarbon industry cycles, with high rental property demand from sector workers from across the country.',
    barrios: ['Centro', 'Rada Tilly', 'Don Bosco', 'Km 3', 'Km 8'],
  },
  'San Fernando del Valle de Catamarca': {
    es: 'San Fernando del Valle de Catamarca, capital provincial, ofrece un mercado inmobiliario muy accesible con creciente demanda por la expansión minera regional. Es una ciudad tranquila con clima árido, ideal para quienes buscan propiedades de bajo precio en el NOA.',
    en: 'San Fernando del Valle de Catamarca, the provincial capital, offers a very affordable real estate market with growing demand from regional mining expansion. It\'s a quiet city with an arid climate, ideal for those seeking low-price properties in the NOA.',
    barrios: ['Centro', 'Banda de Varela', 'Valle Viejo', 'El Portezuelo'],
  },
  'Mendoza': {
    es: 'Mendoza capital es la puerta de los Andes y la capital del vino latinoamericano. Su mercado inmobiliario opera principalmente en dólares con precios altos por la demanda turística e inversora internacional. Las mejores propiedades se concentran en el Gran Mendoza: Godoy Cruz, Luján de Cuyo y Maipú.',
    en: 'Mendoza capital is the gateway to the Andes and Latin America\'s wine capital. Its real estate market operates mainly in USD with high prices due to international tourist and investor demand. The best properties concentrate in Greater Mendoza: Godoy Cruz, Luján de Cuyo, and Maipú.',
    barrios: ['Centro', 'Godoy Cruz', 'Luján de Cuyo', 'Maipú', 'Chacras de Coria', 'El Challao'],
  },
  'Santiago del Estero': {
    es: 'Santiago del Estero, la ciudad más antigua de Argentina (fundada en 1553), ofrece propiedades a precios muy accesibles. Es un mercado en transformación con inversión pública creciente en infraestructura y desarrollo urbano.',
    en: 'Santiago del Estero, Argentina\'s oldest city (founded in 1553), offers properties at very affordable prices. It\'s a market in transformation with growing public investment in infrastructure and urban development.',
    barrios: ['Centro', 'Madre de Ciudades', 'Villa del Parque', 'Belgrano'],
  },
  'Río Cuarto': {
    es: 'Río Cuarto es la segunda ciudad de Córdoba y un importante polo educativo con la Universidad Nacional de Río Cuarto. Su mercado inmobiliario tiene alta demanda de alquileres por la población estudiantil y es una de las ciudades con mejor relación precio/calidad del interior cordobés.',
    en: 'Río Cuarto is Córdoba\'s second city and an important educational hub with the National University of Río Cuarto. Its real estate market has high rental demand from the student population and is one of the interior cities with the best price/quality ratio.',
    barrios: ['Centro', 'Alberdi', 'Banda Norte', 'Parque Norte'],
  },
  'La Rioja': {
    es: 'La Rioja capital ofrece algunas de las propiedades más accesibles en dólares de Argentina. Con un clima árido y soleado y acceso a las Sierras de Velasco, es un destino emergente para quienes buscan calidad de vida a bajo costo en el NOA.',
    en: 'La Rioja capital offers some of Argentina\'s most affordable USD properties. With an arid, sunny climate and access to the Velasco Sierras, it\'s an emerging destination for those seeking quality of life at low cost in the NOA.',
    barrios: ['Centro', 'Villa del Parque', 'Barrio Rivadavia', 'El Prado'],
  },
  'Formosa': {
    es: 'Formosa capital, la ciudad más septentrional de Argentina, ofrece propiedades a precios muy bajos con fuerte demanda de empleados públicos y familias locales. Fronteriza con Paraguay, tiene un mercado comercial binacional que dinamiza la economía local.',
    en: 'Formosa capital, Argentina\'s northernmost city, offers properties at very low prices with strong demand from public employees and local families. Bordering Paraguay, it has a binational commercial market that drives the local economy.',
    barrios: ['Centro', 'San Martín', 'Villa del Carmen', 'Los Esteros'],
  },
  'Cafayate': {
    es: 'Cafayate es la capital vitivinícola del norte argentino, enclavada en los Valles Calchaquíes a 1.683 msnm. Sus bodegas producen el famoso Torrontés, uva insignia de Argentina. El mercado inmobiliario está en pleno auge: bodegas boutique, chalets y fincas con viñedos atraen a inversores nacionales e internacionales. Alta demanda de alquiler temporario con turistas todo el año.',
    en: 'Cafayate is northern Argentina\'s wine capital, nestled in the Calchaquí Valleys at 1,683m above sea level. Its wineries produce the famous Torrontés, Argentina\'s signature grape. The real estate market is booming: boutique wineries, chalets, and vineyard estates attract local and international investors. High year-round short-term rental demand.',
    barrios: ['Centro', 'El Divisadero', 'Chañarmuyo', 'Los Médanos'],
  },
  'Tilcara': {
    es: 'Tilcara es una de las joyas de la Quebrada de Humahuaca, declarada Patrimonio de la Humanidad por la UNESCO en 2003. A 2.461 msnm, combina arqueología precolombina (el Pucará), naturaleza andina y una escena artística vibrante. El mercado inmobiliario crece con fuerza: turistas que se enamoran del lugar y eligen quedarse impulsan la demanda de propiedades para vivir y para alquiler temporario.',
    en: 'Tilcara is one of the gems of the UNESCO World Heritage Quebrada de Humahuaca. At 2,461m above sea level, it combines pre-Columbian archaeology (the Pucará), Andean nature, and a vibrant arts scene. The real estate market is growing fast: tourists who fall in love with the place and choose to stay drive demand for properties to live in and for short-term rental.',
    barrios: ['Centro', 'El Jardín', 'La Banda', 'Calle Bolívar'],
  },
  'Purmamarca': {
    es: 'Purmamarca, famosa por el Cerro de los Siete Colores, es uno de los destinos turísticos más fotogénicos de Argentina. Su pequeño mercado inmobiliario (pocas propiedades disponibles) tiene alta demanda de inversores que buscan alojamientos boutique y posadas para el turismo de alto nivel. Una de las localidades con mayor precio por m² del NOA.',
    en: 'Purmamarca, famous for the Hill of Seven Colors, is one of Argentina\'s most photogenic tourist destinations. Its small real estate market (few available properties) has high investor demand for boutique accommodations and guesthouses for upscale tourism. One of the localities with the highest price per m² in the NOA.',
    barrios: ['Centro', 'Calle Los Alisos'],
  },
  'San Martín de los Andes': {
    es: 'San Martín de los Andes, en el corazón del Parque Nacional Lanín, es considerada por muchos la ciudad más bella de la Patagonia. Con arquitectura de estilo alpino, lagos, volcanes y nieve en invierno, su mercado inmobiliario opera en dólares con demanda sostenida de segunda residencia, alquiler temporario e inversión hotelera. Alternativa más auténtica a Bariloche.',
    en: 'San Martín de los Andes, in the heart of Lanín National Park, is considered by many the most beautiful city in Patagonia. With alpine-style architecture, lakes, volcanoes, and winter snow, its real estate market operates in USD with sustained demand for second homes, short-term rentals, and hotel investment. A more authentic alternative to Bariloche.',
    barrios: ['Centro', 'Chapelco', 'El Arenal', 'Barrio Inacayal'],
  },
  'Villa La Angostura': {
    es: 'Villa La Angostura, en la Ruta de los Siete Lagos, es un exclusivo destino patagónico conocido como "el jardín de la Patagonia". Su entorno natural incomparable (bosque nativo, lago Nahuel Huapi, Parque Nacional Los Arrayanes) impulsa un mercado inmobiliario premium con propiedades en dólares y alta demanda de alquiler temporario de lujo.',
    en: 'Villa La Angostura, on the Seven Lakes Route, is an exclusive Patagonian destination known as "the garden of Patagonia". Its incomparable natural setting (native forest, Lake Nahuel Huapi, Los Arrayanes National Park) drives a premium real estate market with USD-priced properties and high luxury short-term rental demand.',
    barrios: ['Centro', 'Las Balsas', 'El Cruce', 'Barrio Norte'],
  },
  'Junín de los Andes': {
    es: 'Junín de los Andes es la capital de la trucha de Argentina, conocida por su pesca con mosca de clase mundial en el río Chimehuin y el Parque Nacional Lanín. Mercado inmobiliario tranquilo pero en crecimiento, con demanda de propiedades rurales, cabañas y terrenos. Excelente relación precio/calidad respecto a San Martín de los Andes.',
    en: 'Junín de los Andes is Argentina\'s trout capital, known for world-class fly fishing on the Chimehuin river and Lanín National Park. Quiet but growing real estate market, with demand for rural properties, cabins, and land. Excellent price/quality ratio compared to San Martín de los Andes.',
    barrios: ['Centro', 'Los Sauces', 'Barrio Ruca Hue'],
  },
  'El Bolsón': {
    es: 'El Bolsón es la capital de la artesanía y la vida alternativa en la Patagonia. Enclavada en un valle con microclima benigno (llamado "el Bolsón" por estar protegido de los vientos patagónicos), atrae a hippies, artistas, trabajadores remotos y jubilados. Su mercado inmobiliario es uno de los más dinámicos del sur: terrenos, cabañas y casas con huerta en alta demanda.',
    en: 'El Bolsón is the artisan and alternative living capital of Patagonia. Nestled in a valley with a mild microclimate (called "the Pocket" for being sheltered from Patagonian winds), it attracts hippies, artists, remote workers, and retirees. Its real estate market is one of the most dynamic in the south: land, cabins, and houses with vegetable gardens in high demand.',
    barrios: ['Centro', 'El Mallín Ahogado', 'Cerro Lindo', 'El Foyel'],
  },
  'El Calafate': {
    es: 'El Calafate es la puerta de entrada al Parque Nacional Los Glaciares y el Glaciar Perito Moreno (Patrimonio UNESCO). Con turismo internacional de altísimo nivel y temporadas marcadas (verano e invierno), su mercado inmobiliario premium opera en dólares con retornos de alquiler temporario entre los más altos de Argentina. Escasez de suelo y regulaciones limitan la oferta.',
    en: 'El Calafate is the gateway to Los Glaciares National Park and the Perito Moreno Glacier (UNESCO Heritage). With high-level international tourism and marked seasons (summer and winter), its premium real estate market operates in USD with short-term rental returns among Argentina\'s highest. Land scarcity and regulations limit supply.',
    barrios: ['Centro', 'Barrio Aeropuerto', 'Barrio Mitre', 'La Lomita'],
  },
  'El Chaltén': {
    es: 'El Chaltén es el capital nacional del trekking argentino, ubicada frente al emblemático Fitz Roy en la Patagonia austral. Es el pueblo más joven de Argentina (fundado en 1985) y su mercado inmobiliario es muy pequeño pero de altísimo valor. Las propiedades disponibles se venden en dólares y tienen una demanda global por su posicionamiento como destino top del turismo de aventura mundial.',
    en: 'El Chaltén is Argentina\'s national trekking capital, located facing the iconic Fitz Roy in southern Patagonia. It\'s Argentina\'s youngest town (founded in 1985) and its real estate market is very small but extremely high-value. Available properties sell in USD and have global demand for their positioning as a top world adventure tourism destination.',
    barrios: ['Centro', 'Barrio Lago Del Desierto'],
  },
  'Puerto Madryn': {
    es: 'Puerto Madryn es la capital del avistaje de ballenas en Sudamérica. Su bahía alberga a la ballena franca austral entre junio y diciembre, atrayendo miles de turistas. Con una economía sólida basada en pesca, aluminio (Aluar) y turismo, su mercado inmobiliario es estable y en crecimiento. Ideal para segunda residencia costera y alquiler temporario.',
    en: 'Puerto Madryn is South America\'s whale watching capital. Its bay hosts the southern right whale between June and December, attracting thousands of tourists. With a solid economy based on fishing, aluminum (Aluar), and tourism, its real estate market is stable and growing. Ideal for coastal second homes and short-term rentals.',
    barrios: ['Centro', 'El Doradillo', 'Rocas Coloradas', 'Patagonia Park'],
  },
  'Trelew': {
    es: 'Trelew, corazón de la colonización galesa en la Patagonia, es un importante centro industrial y comercial del Chubut. Con el aeropuerto regional más importante de la Patagonia atlántica, es la puerta de acceso a la Península Valdés. Su mercado inmobiliario ofrece propiedades más accesibles que las ciudades costeras premium.',
    en: 'Trelew, the heart of Welsh colonization in Patagonia, is an important industrial and commercial center of Chubut. With the most important regional airport in Atlantic Patagonia, it\'s the gateway to Valdés Peninsula. Its real estate market offers more affordable properties than premium coastal cities.',
    barrios: ['Centro', 'Ciudadela', 'Planta Industrial', 'Barrio San Pablo'],
  },
  'Puerto Iguazú': {
    es: 'Puerto Iguazú, frente a las Cataratas del Iguazú (Maravilla Natural del Mundo), recibe más de 1.5 millones de turistas al año. Su mercado inmobiliario se enfoca principalmente en alojamientos turísticos, hostels, hoteles boutique y propiedades para alquiler temporario. Triple frontera (Argentina-Brasil-Paraguay) genera demanda comercial adicional.',
    en: 'Puerto Iguazú, facing the Iguazú Falls (Wonder of the Natural World), receives over 1.5 million tourists per year. Its real estate market focuses mainly on tourist accommodations, hostels, boutique hotels, and short-term rental properties. The Triple Frontier (Argentina-Brazil-Paraguay) generates additional commercial demand.',
    barrios: ['Centro', 'Bº Unión', 'Andresito', 'Barrio San Martín'],
  },
  'Mina Clavero': {
    es: 'Mina Clavero, en las Sierras de Traslasierra (Córdoba), es uno de los destinos de verano más populares de Argentina. Sus ríos de agua cristalina, el Pinar (bosque de pinos único) y el turismo familiar la convierten en un mercado de segunda residencia muy activo. Alta demanda de alquiler temporario en temporada alta (diciembre-marzo).',
    en: 'Mina Clavero, in Córdoba\'s Traslasierra Sierras, is one of Argentina\'s most popular summer destinations. Its crystal-clear rivers, the Pinar (unique pine forest), and family tourism make it a very active second-home market. High short-term rental demand in peak season (December-March).',
    barrios: ['Centro', 'Villa Cura Brochero', 'Nono', 'Los Hornillos'],
  },
  'La Falda': {
    es: 'La Falda, en las Sierras Chicas de Córdoba, es un clásico destino turístico a 80km de la capital. Conocida por el Hotel Eden (donde se hospedó Einstein) y sus paisajes serranos, ofrece propiedades residenciales y de alquiler temporario a precios más accesibles que Villa Carlos Paz.',
    en: 'La Falda, in Córdoba\'s Sierras Chicas, is a classic tourist destination 80km from the capital. Known for the Hotel Eden (where Einstein stayed) and its mountain landscapes, it offers residential and short-term rental properties at more affordable prices than Villa Carlos Paz.',
    barrios: ['Centro', 'Las Jarillas', 'El Diquecito', 'Huerta Grande'],
  },
  'Cosquín': {
    es: 'Cosquín es la capital nacional del folklore argentino, sede del famoso Festival Nacional de Folklore. A 64km de Córdoba capital, ofrece propiedades a precios accesibles con alta demanda de alquiler temporario en enero (durante el festival) y turismo serrano todo el año.',
    en: 'Cosquín is Argentina\'s national folklore capital, home to the famous National Folklore Festival. 64km from Córdoba capital, it offers affordable properties with high short-term rental demand in January (during the festival) and mountain tourism year-round.',
    barrios: ['Centro', 'La Toma', 'El Empalme', 'Villa Warcalde'],
  },
  'Santa Rosa de Calamuchita': {
    es: 'Santa Rosa de Calamuchita, a orillas del lago Los Molinos en el Valle de Calamuchita (Córdoba), es el corazón del turismo de lagos serranos. Con más de 100km de costa lacustre, atrae a familias, inversores de alquiler temporario y compradores de segunda residencia. Crecimiento inmobiliario sostenido los últimos 10 años.',
    en: 'Santa Rosa de Calamuchita, on the shores of Lake Los Molinos in Córdoba\'s Calamuchita Valley, is the heart of the lake and mountain tourism scene. With more than 100km of lake coast, it attracts families, short-term rental investors, and second-home buyers. Sustained real estate growth over the last 10 years.',
    barrios: ['Centro', 'Los Reartes', 'Villa General Belgrano', 'La Cumbrecita'],
  },
  'Tandil': {
    es: 'Tandil, en las Sierras de Tandilia (Buenos Aires), es el epicentro del turismo gourmet y de naturaleza bonaerense. Famosa por su queso, salame y dulce de leche artesanal, Tandil atrae a porteños y turistas de alto poder adquisitivo todo el año. Su mercado inmobiliario combina propiedades residenciales, casas de campo y alojamientos boutique en pleno auge.',
    en: 'Tandil, in Buenos Aires\' Tandilia Sierras, is the epicenter of gourmet and nature tourism in the Buenos Aires province. Famous for its artisan cheese, salami, and dulce de leche, Tandil attracts affluent Buenos Aires residents and tourists year-round. Its real estate market combines residential properties, country houses, and boutique accommodations in full growth.',
    barrios: ['Centro', 'Cerro El Centinela', 'Don Bosco', 'Villa Italia'],
  },
  'Pinamar': {
    es: 'Pinamar es el balneario premium del litoral atlántico bonaerense, conocido por sus casas entre pinos en primera línea de playa. Con Valeria del Mar y Ostende como vecinos exclusivos, Pinamar concentra la demanda de veraneos de alto nivel y propiedades de segunda residencia más caras de la costa argentina. El mercado en dólares es muy activo en temporada.',
    en: 'Pinamar is the premium seaside resort of the Buenos Aires Atlantic coast, known for its pine-framed beachfront homes. With Valeria del Mar and Ostende as exclusive neighbors, Pinamar concentrates demand for high-end summer vacations and the most expensive second-home properties on the Argentine coast. The USD market is very active in season.',
    barrios: ['Pinamar Centro', 'Valeria del Mar', 'Ostende', 'Cariló'],
  },
  'Villa Gesell': {
    es: 'Villa Gesell, fundada por Carlos Idaho Gesell como proyecto utópico forestal, es uno de los balnearios más populares del litoral atlántico. Con un perfil más familiar y joven que Pinamar, ofrece propiedades a precios más accesibles y alta demanda de alquiler temporario en verano. Posición ideal para el turismo masivo de enero.',
    en: 'Villa Gesell, founded by Carlos Idaho Gesell as a utopian forestry project, is one of the most popular seaside resorts on the Atlantic coast. With a more family-friendly and youthful profile than Pinamar, it offers more affordable properties and high short-term rental demand in summer. Ideal position for mass January tourism.',
    barrios: ['Centro', 'Mar Azul', 'Mar de las Pampas', 'Las Gaviotas'],
  },
  'Cariló': {
    es: 'Cariló es el destino exclusivo por excelencia del litoral atlántico argentino. Sin carteles publicitarios, sin bares ruidosos y con casas de diseño entre pinos centenarios, es el balneario favorito de la élite argentina. Su mercado inmobiliario opera en dólares con algunas de las propiedades más caras del país fuera de Buenos Aires y Mendoza.',
    en: 'Cariló is the quintessential exclusive destination of the Argentine Atlantic coast. With no advertising signs, no loud bars, and designer homes among century-old pines, it\'s the favorite seaside resort of the Argentine elite. Its real estate market operates in USD with some of the country\'s most expensive properties outside Buenos Aires and Mendoza.',
    barrios: ['Cariló Centro', 'La Alameda', 'Las Acacias'],
  },
};
